spring:
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    password: postgres1234
  application:
    name: Aplicacao REST de um Banco Digital
server:
  port: '27031'